---
title: "Spektren Testpartikel Korallen"
author: "Julia Prume"
date: '2022-06-20'
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Preparation

### Load Libraries

```{r setup}
library(tidyverse)
library(skimr)
```

### Load Data

```{r}
pa <- read.csv(file = "EXTRACT_PA.0.dpt", header = FALSE)
pe <- read.csv(file = "EXTRACT_PE.0.dpt", header = FALSE)
pet <- read.csv(file = "EXTRACT_PET.0.dpt", header = FALSE)
pp <- read.csv(file = "EXTRACT_PP.0.dpt", header = FALSE)
ps <- read.csv(file = "EXTRACT_PS.0.dpt", header = FALSE)
pvc <- read.csv(file = "EXTRACT_PVC.0.dpt", header = FALSE)
```

## Plot all polymer types together

### Make data tidy

```{r}

pvc <- pvc + 0.2
ps <- ps + 0.4
pp <- pp + 0.6
pa <- pa + 0.8
pet <- pet + 1

df <- rbind(pet, pa, pp, ps, pvc, pe)

df %>% 
  rename("Wavenumber" = V1) %>% 
  rename("Absorption" = V2) -> df

sample <- factor(c(rep("PE", 1889), rep("PVC", 1889), rep("PS", 1889), rep("PP", 1889), rep("PA", 1889), rep("PET", 1889)))

spectra <- tibble(df, sample)
```

### Format plot

```{r}
theme <- theme(panel.border = element_rect(linetype = "solid", fill = NA),
               panel.background = element_rect(fill = NA),
               axis.text = element_text(size = 10),
               axis.text.y = element_blank(),
               axis.ticks.y = element_blank(),
               axis.title.x = element_text(size = rel(1.1)),
               axis.title.y = element_text(size = rel(1.1)),
               legend.position = "right",
               legend.key = element_blank())
```

### Plot data

```{r}
p1 <- ggplot(data = spectra,
       mapping = aes(x = Wavenumber,
                     y = Absorption,
                     color = sample)) +
  geom_line(aes(col = sample), size = 1) +
  labs(x = expression(Wavenumber / cm^{-1}),
       y = "Absorption / a. u.\n") +
  scale_color_manual(name = "", 
                     values = c("PE" = "#0A0A0A", "PVC" = "#6F6E69", "PS" = "#D3D2C7", 
                                "PP" = "#EBF779", "PET" = "#2D2DB4","PA" = "#C23E3E"),                      
                     breaks = c("PE", "PVC", "PS", "PP", "PA", "PET")) +
  scale_x_reverse() +
  coord_cartesian(ylim = c(0, 1.15), xlim = c(3490, 950))

(p1 <- p1 + theme)
ggsave("FTIR-Spektren.png", plot = p1, width = 7, height = 6)
```
